services:
  - type: web
    name: finflare
    env: python
    buildCommand: pip install -r requirements.txt && cd frontend && npm install && npm run build && cd .. && python manage.py migrate
    startCommand: gunicorn webapps.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: webapps.settings
      - key: DATABASE_URL
        fromDatabase:
          name: finflare-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False

databases:
  - name: finflare-db
    databaseName: finflare
    user: finflare
    plan: free 