# Generated by Django 4.2.20 on 2025-03-19 14:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('user_amt', models.DecimalField(decimal_places=2, max_digits=1000000000000)),
                ('roi', models.DecimalField(decimal_places=2, max_digits=100000000000)),
                ('growth_rate', models.DecimalField(decimal_places=2, max_digits=1000000000)),
                ('risk_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_article', models.CharField(max_length=200)),
                ('publishing_date', models.DateTimeField()),
                ('author', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=10000000000)),
                ('savings', models.DecimalField(decimal_places=2, max_digits=100000000000)),
                ('current_employment', models.CharField(max_length=200)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('retirement_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finflare.investments')),
            ],
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('transaction_date', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finflare.profile')),
            ],
        ),
        migrations.AddField(
            model_name='investments',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finflare.profile'),
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_goal', models.CharField(max_length=200)),
                ('goals_type', models.CharField(max_length=100)),
                ('goal_date', models.DateField()),
                ('priority', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amt', models.DecimalField(decimal_places=2, max_digits=10000000000)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finflare.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BankingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=100000000)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
