# Generated by Django 4.2.20 on 2025-03-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finflare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='name_goal',
            new_name='goal_name',
        ),
        migrations.RemoveField(
            model_name='goals',
            name='goals_type',
        ),
        migrations.RemoveField(
            model_name='investments',
            name='invest_type',
        ),
        migrations.AddField(
            model_name='goals',
            name='type_of_goal',
            field=models.CharField(choices=[('save_money', 'Save Money'), ('buy_house', 'Buy a House'), ('pay_debt', 'Pay Off Debt'), ('emergency_fund', 'Emergency Fund'), ('not_set', 'None for now!')], default='not_set', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investments',
            name='investment_type',
            field=models.CharField(choices=[('stocks', 'Stocks'), ('bonds', 'Bonds'), ('mutual_funds', 'Mutual Funds'), ('real_estate', 'Real Estate'), ('crypto', 'Crypto'), ('not_set', 'None for now!')], default='not_set', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
