# Generated by Django 4.2.20 on 2025-03-19 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finflare', '0002_rename_name_goal_goals_goal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000000000, null=True),
        ),
        migrations.AlterField(
            model_name='goals',
            name='goal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goals',
            name='goal_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='goals',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='goals',
            name='type_of_goal',
            field=models.CharField(blank=True, choices=[('save_money', 'Save Money'), ('buy_house', 'Buy a House'), ('pay_debt', 'Pay Off Debt'), ('emergency_fund', 'Emergency Fund'), ('not_set', 'None for now!')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='growth_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000000000, null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='investment_type',
            field=models.CharField(blank=True, choices=[('stocks', 'Stocks'), ('bonds', 'Bonds'), ('mutual_funds', 'Mutual Funds'), ('real_estate', 'Real Estate'), ('crypto', 'Crypto'), ('not_set', 'None for now!')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='risk_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='roi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100000000000, null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='user_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000000000000, null=True),
        ),
    ]
