# Generated by Django 4.2.20 on 2025-03-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finflare', '0003_alter_goals_amt_alter_goals_goal_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investments',
            old_name='name',
            new_name='investment_name',
        ),
    ]
