# Generated by Django 4.2.20 on 2025-04-10 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finflare", "0005_profile_is_complete_alter_profile_age_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIGeneratedTips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tips_content", models.TextField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user_data_hash",
                    models.CharField(
                        help_text="Hash of user data to detect changes", max_length=64
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
