# Generated by Django 5.2 on 2025-04-16 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finflare', '0007_spending_investment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spending',
            old_name='investment_type',
            new_name='spending_type',
        ),
    ]
